// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetNatureIDOrNameRequest struct {
	// The ID or name of the Nature to retrieve
	IDOrName string `pathParam:"style=simple,explode=false,name=idOrName"`
}

func (o *GetNatureIDOrNameRequest) GetIDOrName() string {
	if o == nil {
		return ""
	}
	return o.IDOrName
}

type GetNatureIDOrNameResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetNatureIDOrNameResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetNatureIDOrNameResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetNatureIDOrNameResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
